########
# NetLab
########

tag: Null
random_seed: 0

##############
# Dataloader #
##############

# cifar10, imagewoof
dataloader:
  dataset: "cifar10"
  num_workers: 2

########
# Data #
########

data:
  num_classes: Null
  input_shape: Null

#########
# Model #
#########

convnet:
  num_channels_hidden: 16
  num_channels_out: 8
  num_blocks: 4

densenet:
  patch_size: 2
  embedding_channels: 16
  num_dim_hidden: 256
  num_blocks: 2
  num_hidden: 2

###########
# Trainer #
###########

trainer:
  device: "gpu"   # gpu, cpu
  n_epochs: 10
  learning_rate: 3.0e-4
  weight_decay: 0
  lr_step_size: 2
  lr_gamma: 0.5
  batch_size: 512

###########
# Summary #
###########

summary:
  add_graph: true
  add_sample_batch: true
  add_hparams: true
  add_train_stats_every_n_epochs: 1
  add_test_stats_every_n_epochs: 2
  add_weights_every_n_epochs: true
  add_params_hist_every_n_epochs: true
  add_model_every_n_epochs: true

checkpoints:
  load_model: 0
  model_path: 0

###############
# Directories #
###############

dirs:
  data: "data"
  runs: "runs"
  weights: "weights"
